export const backoffice: {
    'components/OrderLineEdit': typeof OrderLineEdit;
    'components/OrderList': typeof OrderList;
    'components/OrderRelationshipSelect': typeof OrderRelationshipSelect;
    'components/ProductList': typeof ProductList;
    'components/ProductRelationshipSelect': typeof ProductRelationshipSelect;
    'pages/OrderIndexPage': typeof OrderIndexPage;
    'pages/OrderShowPage': typeof OrderShowPage;
    'pages/ProductIndexPage': typeof ProductIndexPage;
    'pages/ProductShowPage': typeof ProductShowPage;
    'states/OrderLineEditState': typeof OrderLineEditState;
};
import OrderLineEdit from "./components/OrderLineEdit";
import OrderList from "./components/OrderList";
import OrderRelationshipSelect from "./components/OrderRelationshipSelect";
import ProductList from "./components/ProductList";
import ProductRelationshipSelect from "./components/ProductRelationshipSelect";
import OrderIndexPage from "./pages/OrderIndexPage";
import OrderShowPage from "./pages/OrderShowPage";
import ProductIndexPage from "./pages/ProductIndexPage";
import ProductShowPage from "./pages/ProductShowPage";
import OrderLineEditState from "./states/OrderLineEditState";
