export const backoffice: {
    'components/AbstractList': typeof AbstractList;
    'components/AbstractRelationshipSelect': typeof AbstractRelationshipSelect;
    'components/BackofficeNav': typeof BackofficeNav;
    'components/OrderLineEdit': typeof OrderLineEdit;
    'components/OrderList': typeof OrderList;
    'components/OrderRelationshipSelect': typeof OrderRelationshipSelect;
    'components/PermanentDeleteButton': typeof PermanentDeleteButton;
    'components/ProductList': typeof ProductList;
    'components/ProductRelationshipSelect': typeof ProductRelationshipSelect;
    'components/SoftDeleteButton': typeof SoftDeleteButton;
    'components/SubmitButton': typeof SubmitButton;
    'components/UserList': typeof UserList;
    'components/UserRelationshipSelect': typeof UserRelationshipSelect;
    'components/UserSortDropdown': typeof UserSortDropdown;
    'pages/DashboardPage': typeof DashboardPage;
    'pages/OrderIndexPage': typeof OrderIndexPage;
    'pages/OrderShowPage': typeof OrderShowPage;
    'pages/ProductIndexPage': typeof ProductIndexPage;
    'pages/ProductShowPage': typeof ProductShowPage;
    'pages/UserIndexPage': typeof UserIndexPage;
    'pages/UserShowPage': typeof UserShowPage;
    'states/OrderLineEditState': typeof OrderLineEditState;
    'states/UserListState': typeof UserListState;
};
import AbstractList from "./components/AbstractList";
import AbstractRelationshipSelect from "./components/AbstractRelationshipSelect";
import BackofficeNav from "./components/BackofficeNav";
import OrderLineEdit from "./components/OrderLineEdit";
import OrderList from "./components/OrderList";
import OrderRelationshipSelect from "./components/OrderRelationshipSelect";
import PermanentDeleteButton from "./components/PermanentDeleteButton";
import ProductList from "./components/ProductList";
import ProductRelationshipSelect from "./components/ProductRelationshipSelect";
import SoftDeleteButton from "./components/SoftDeleteButton";
import SubmitButton from "./components/SubmitButton";
import UserList from "./components/UserList";
import UserRelationshipSelect from "./components/UserRelationshipSelect";
import UserSortDropdown from "./components/UserSortDropdown";
import DashboardPage from "./pages/DashboardPage";
import OrderIndexPage from "./pages/OrderIndexPage";
import OrderShowPage from "./pages/OrderShowPage";
import ProductIndexPage from "./pages/ProductIndexPage";
import ProductShowPage from "./pages/ProductShowPage";
import UserIndexPage from "./pages/UserIndexPage";
import UserShowPage from "./pages/UserShowPage";
import OrderLineEditState from "./states/OrderLineEditState";
import UserListState from "./states/UserListState";
